exercises/1-aspdotnetcore-web-application-building-m1-exercise-files/BethanysPieShop/src/BethanysPieShop/Controllers/PieController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using BethanysPieShop.Models;
using BethanysPieShop.ViewModels;
using System;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace BethanysPieShop.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
        }

        //public ViewResult List()
        //{
        //    return View(_pieRepository.Pies);
        //}

        public ViewResult List(string category)
        {
            IEnumerable<Pie> pies;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                pies = _pieRepository.Pies.OrderBy(p => p.PieId);
                currentCategory = "All pies";
            }
            //else if (category == "All")
            //{
            //    pies = _pieRepository.Pies.OrderBy(p => p.PieId);
            //}
            else
            {
                pies = _pieRepository.Pies.Where(p => p.Category.CategoryName == category)
                   .OrderBy(p => p.PieId);
                currentCategory = _categoryRepository.Categories.FirstOrDefault(c => c.CategoryName == category).CategoryName;
            }

            return View(new PiesListViewModel
            {
                Pies = pies,
                CurrentCategory = currentCategory
            });
        }

        [Route("[controller]/Details/{id}")]
        public IActionResult Details(int id)
        {
            var pie = _pieRepository.GetPieById(id);
            if (pie == null)
                return NotFound();

            return View(pie);
        }
    }
}

exercises/1-aspdotnetcore-web-application-building-m1-exercise-files/BethanysPieShop/src/BethanysPieShop/Views/Shared/Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

exercises/1-aspdotnetcore-web-application-building-m1-exercise-files/BethanysPieShop/src/BethanysPieShop/Views/Shared/PieList.cshtml
@model IEnumerable<Pie>

@foreach (var pie in @Model)
{
    @*<li class="container">
        <strong><a asp-controller="Pie" asp-action="Details" asp-route-id="@pie.PieId">@pie.Name</a></strong>
        <span class="pull-right label label-primary">
            @pie.Price.ToString("c")
        </span>
        <span class="lead">@pie.ShortDescription</span>

        <p class="button">
            <a asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
               asp-route-pieId="@pie.PieId">Add to cart</a>
        </p>
    </li>*@

    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="@pie.ImageThumbnailUrl" alt="">
            <div class="caption">
                <h3 class="pull-right">@pie.Price.ToString("c")</h3>
                <h3>
                    <a asp-controller="Pie" asp-action="Details" asp-route-id="@pie.PieId">@pie.Name</a>
                </h3>
                <p>@pie.ShortDescription</p>
            </div>
            <div class="addToCart">
                <p class="button">
                    <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
                       asp-route-pieId="@pie.PieId">Add to cart</a>
                </p>
            </div>
        </div>
    </div>
}
<a asp-controller="Pie" asp-action="LoadExtra">Loading...</a>

exercises/1-aspdotnetcore-web-application-building-m1-exercise-files/BethanysPieShop/src/BethanysPieShop/Views/Shared/PieOfTheWeekSummary.cshtml
@model Pie

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="">
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Pie" asp-action="Details" asp-route-id="@Model.PieId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
                   asp-route-pieId="@Model.PieId">Add to cart</a>
            </p>
        </div>
    </div>
</div>

exercises/1-aspdotnetcore-web-application-building-m1-exercise-files/BethanysPieShop/src/BethanysPieShop/Views/Shared/PieOverviewSummary.cshtml
@model Pie

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="">
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Pie" asp-action="Details" asp-route-id="@Model.PieId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"  
                   asp-route-pieId="@Model.PieId">Add to cart</a>
            </p>
        </div>
    </div>
</div>

exercises/1-aspdotnetcore-web-application-building-m1-exercise-files/BethanysPieShop/src/BethanysPieShop/Views/Shared/_Layout - old.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Bethany's Pie Shop</title>
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" /><!-- TODO: check wat er naar environments moet-->
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">@AppSettings.Value.SiteTitle</a>*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @await Component.InvokeAsync("CategoryMenu")
                    @await Component.InvokeAsync("ShoppingCartSummary")
                    <li><a asp-controller="Contact" asp-action="Index">Contact us</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>

        </div>
    </div>
    @*<div class="navbar navbar-inverse" role="navigation">
            <a class="navbar-brand" href="#">Bethany's Pie Shop</a>
        </div>*@
    <div class="container body-content">
        @*<div id="categories" class="col-xs-3">
                Put something useful here later
            </div>*@
        <div class="col-xs-12">
            @RenderBody()
        </div>
    </div>

    <environment names="Development">
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

exercises/1-aspdotnetcore-web-application-building-m1-exercise-files/BethanysPieShop/src/BethanysPieShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bethany's Pie Shop</title>
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <script src="~/lib/jquery/dist/jquery.js"></script>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @await Component.InvokeAsync("CategoryMenu")
                    <li><a asp-controller="Contact" asp-action="Index">Contact us</a></li>
                    @await Component.InvokeAsync("ShoppingCartSummary")
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>


    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" alt="Bethany's Pie Shop'" src="~/Images/bethanylogo.png" />
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>

    <environment names="Development">
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment names="Production">
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>